// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylocpaefxyaifpcfvkwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsb2NwYWVmeHlhaWZwY2Z2a3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzM0NTcsImV4cCI6MjA3MDk0OTQ1N30.eeb473Cj-Se86N5uJ25LSNmJX-fGwuzxoGZL05FsnNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});